spring:
  application:
    name: NetCap Viasat
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

netcap:
  connection:
    socket:
      port: 50000
      host: localhost
